name: 一键清除所有Actions记录
on:

  # 仅手动触发，避免误删

  workflow_dispatch:

permissions:

  # 必须配置删除权限

  actions: write

jobs:
  full-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: mattrax/github-actions-cleanup-action@v1
        with:

          # 0天规则=全量删除所有历史记录

          older_than: 0d

          # 不限制工作流，清空所有工作流的记录

          workflow: ""

          # 不限制状态，删除所有状态的记录

          status: ""