name: 清理指定工作流记录
on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '0 0 * * 0' # 可选配置每周日自动执行清理
jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 批量删除指定工作流记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow_patterns: "" # 精准指定要清理的工作流
          retain_days: 0 # 删除7天前的旧记录
          keep_minimum_runs: 1 # 至少保留最近3条运行记录